runtime: python39  
service: fe-069  
instance_class: F1  

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: \1
    upload: (.*)

default_expiration: "1h"  