steps:
  # Komponen 1
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - app
      - deploy
      - app.yaml
      - '--quiet'
    dir: 'frontend'  

# Komponen 2
options:
  logging: CLOUD_LOGGING_ONLY  